info:
  title: Alchemy Transaction Simulation API JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Transaction Simulation API.
  version: 0.0.0
servers:
  - url: https://eth-mainnet.g.alchemy.com/v2
    name: Mainnet
    description: Ethereum Mainnet endpoint for Alchemy Transaction Simulation API
  - url: https://eth-sepolia.g.alchemy.com/v2
    name: Sepolia
