info:
  title: Alchemy BSC JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for BSC.
  version: 0.0.0
servers:
  - url: https://bnb-mainnet.g.alchemy.com/v2/
    name: BSC Mainnet
  - url: https://bnb-testnet.g.alchemy.com/v2/
    name: BSC Testnet
