info:
  title: Alchemy Wallet APIs JSON-RPC spec
  description: A specification of the standard JSON-RPC methods for the Alchemy Wallet APIs.
  version: 0.0.0
servers:
  - url: https://api.g.alchemy.com
