info:
  title: Alchemy Blast JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Blast.
  version: 0.0.0
servers:
  - url: https://blast-mainnet.g.alchemy.com/v2
    name: Blast Mainnet
  - url: https://blast-sepolia.g.alchemy.com/v2
    name: Blast Sepolia
