info:
  title: Alchemy Bundler API JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for the Alchemy Bundler API.
  version: 0.0.0
servers:
  - url: https://eth-mainnet.g.alchemy.com/v2/
    name: Ethereum Mainnet
  - url: https://eth-sepolia.g.alchemy.com/v2/
    name: Ethereum Sepolia
  - url: https://eth-holesky.g.alchemy.com/v2/
    name: Ethereum Holesky
  - url: https://opt-mainnet.g.alchemy.com/v2/
    name: Optimism Mainnet
  - url: https://polygon-mainnet.g.alchemy.com/v2/
    name: Polygon Mainnet
  - url: https://polygon-amoy.g.alchemy.com/v2/
    name: Polygon Amoy
  - url: https://arb-mainnet.g.alchemy.com/v2/
    name: Arbitrum Mainnet
  - url: https://arb-sepolia.g.alchemy.com/v2/
    name: Arbitrum Sepolia
  - url: https://arbnova-mainnet.g.alchemy.com/v2/
    name: Arbitrum Nova
  - url: https://berachain-bartio.g.alchemy.com/v2/
    name: Berachain Bartio
  - url: https://zora-mainnet.g.alchemy.com/v2/
    name: Zora Mainnet
  - url: https://zora-sepolia.g.alchemy.com/v2/
    name: Zora Sepolia
  - url: https://polynomial-mainnet.g.alchemy.com/v2/
    name: Polynomial Mainnet
  - url: https://polynomial-sepolia.g.alchemy.com/v2/
    name: Polynomial Sepolia
  - url: https://base-mainnet.g.alchemy.com/v2/
    name: Base Mainnet
  - url: https://base-sepolia.g.alchemy.com/v2/
    name: Base Sepolia
  - url: https://frax-mainnet.g.alchemy.com/v2/
    name: Frax Mainnet
  - url: https://frax-sepolia.g.alchemy.com/v2/
    name: Frax Sepolia
  - url: https://anime-sepolia.g.alchemy.com/v2/
    name: Anime Sepolia
  - url: https://race-mainnet.g.alchemy.com/v2/
    name: Race Mainnet
  - url: https://shape-mainnet.g.alchemy.com/v2/
    name: Shape Mainnet
  - url: https://worldchain-mainnet.g.alchemy.com/v2/
    name: Worldchain Mainnet
  - url: https://ink-mainnet.g.alchemy.com/v2/
    name: Ink Mainnet
  - url: https://ink-sepolia.g.alchemy.com/v2/
    name: Ink Sepolia
