info:
  title: Alchemy Celo JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Celo.
  version: 0.0.0
servers:
  - url: https://celo-mainnet.g.alchemy.com/v2/
    name: Celo Mainnet
  - url: https://celo-alfajores.g.alchemy.com/v2/
    name: Celo Alfajores
  - url: https://celo-baklava.g.alchemy.com/v2/
    name: Celo Baklava
