info:
  title: Alchemy Transactions Receipt API JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Transactions Receipt API.
  version: 0.0.0
servers:
  - url: https://eth-mainnet.g.alchemy.com/v2
    name: Mainnet
  - url: https://eth-sepolia.g.alchemy.com/v2
    name: Sepolia
