info:
  title: Alchemy Berachain JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Berachain.
  version: 0.0.0
servers:
  - url: https://berachain-mainnet.g.alchemy.com/v2/
    name: Berachain Mainnet
  - url: https://berachain-bepolia.g.alchemy.com/v2/
    name: Berachain Bepolia
