info:
  title: Alchemy Monad JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Monad.
  version: 0.0.0
servers:
  - url: https://monad-testnet.g.alchemy.com/v2
    name: Monad Testnet
