info:
  title: Alchemy Ink JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Ink.
  version: 0.0.0
servers:
  - url: https://ink-mainnet.g.alchemy.com/v2/
    name: Ink Mainnet
  - url: https://ink-sepolia.g.alchemy.com/v2/
    name: Ink Sepolia
