info:
  title: Alchemy Linea JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Linea.
  version: 0.0.0
servers:
  - url: https://linea-mainnet.g.alchemy.com/v2/
    name: Linea Mainnet
  - url: https://linea-sepolia.g.alchemy.com/v2/
    name: Linea Sepolia
