info:
  title: Alchemy Zetachain JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Zetachain.
  version: 0.0.0
servers:
  - url: https://zetachain-mainnet.g.alchemy.com/v2
    name: Zetachain Mainnet
  - url: https://zetachain-testnet.g.alchemy.com/v2
    name: Zetachain Testnet
