info:
  title: Alchemy Solana JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Solana.
  version: 0.0.0
servers:
  - url: https://solana-mainnet.g.alchemy.com/v2
    name: Solana Mainnet
  - url: https://solana-devnet.g.alchemy.com/v2
    name: Solana Devnet
