info:
  title: Alchemy Base JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Base.
  version: 0.0.0
servers:
  - url: https://base-mainnet.g.alchemy.com/v2/
    name: Base Mainnet
  - url: https://base-sepolia.g.alchemy.com/v2/
    name: Base Sepolia
