info:
  title: Alchemy Metis JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Metis.
  version: 0.0.0
servers:
  - url: https://metis-mainnet.g.alchemy.com/v2/
    name: Metis Mainnet
