info:
  title: Alchemy Polygon zkEVM JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Polygon zkEVM.
  version: 0.0.0
servers:
  - url: https://polygonzkevm-mainnet.g.alchemy.com/v2
    name: Polygon zkEVM Mainnet
  - url: https://polygonzkevm-cardona.g.alchemy.com/v2
    name: Polygon zkEVM Cardona
