info:
  title: Alchemy Anime JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Anime.
  version: 0.0.0
servers:
  - url: https://anime-mainnet.g.alchemy.com/v2
    name: Anime Mainnet
  - url: https://anime-sepolia.g.alchemy.com/v2
    name: Anime Sepolia
