info:
  title: Alchemy Mantle JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Mantle.
  version: 0.0.0
servers:
  - url: https://mantle-mainnet.g.alchemy.com/v2/
    name: Mantle Mainnet
  - url: https://mantle-sepolia.g.alchemy.com/v2/
    name: Mantle Sepolia
