info:
  title: Alchemy Starknet JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Starknet.
  version: 0.0.0
servers:
  - url: https://starknet-mainnet.g.alchemy.com/v2
    name: Starknet Mainnet (Default)
  - url: https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/
    name: Starknet Mainnet (v0.8)
  - url: https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/
    name: Starknet Mainnet (v0.7)
  - url: https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_6/
    name: Starknet Mainnet (v0.6)
  - url: https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_5/
    name: Starknet Mainnet (v0.5)
  - url: https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_4/
    name: Starknet Mainnet (v0.4)
