info:
  title: Alchemy Abstract JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Abstract.
  version: 0.0.0
servers:
  - url: https://abstract-mainnet.g.alchemy.com/v2/
    name: Abstract Mainnet
  - url: https://abstract-testnet.g.alchemy.com/v2/
    name: Abstract Testnet
