info:
  title: Alchemy Avalanche JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Avalanche.
  version: 0.0.0
servers:
  - url: https://avax-mainnet.g.alchemy.com/v2
    name: Avalanche Mainnet
  - url: https://avax-fuji.g.alchemy.com/v2
    name: Avalanche Fuji
