info:
  title: Alchemy Optimism JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Optimism.
  version: 0.0.0
servers:
  - url: https://optimism-mainnet.g.alchemy.com/v2
    name: Optimism Mainnet
  - url: https://optimism-sepolia.g.alchemy.com/v2
    name: Optimism Sepolia
