info:
  title: Alchemy Superseed JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Superseed.
  version: 0.0.0
servers:
  - url: https://superseed-mainnet.alchemy-blast.com/v2
    name: Superseed Mainnet
  - url: https://superseed-sepolia.alchemy-blast.com/v2
    name: Superseed Sepolia
