info:
  title: Alchemy Polygon JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Polygon.
  version: 0.0.0
servers:
  - url: https://polygon-mainnet.g.alchemy.com/v2
    name: Polygon Mainnet
  - url: https://polygon-amoy.g.alchemy.com/v2
    name: Polygon Amoy
