info:
  title: Alchemy Story JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Story.
  version: 0.0.0
servers:
  - url: https://story-mainnet.g.alchemy.com/v2
    name: Story Mainnet
