info:
  title: Alchemy Lumia JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Lumia.
  version: 0.0.0
servers:
  - url: https://lumia-prism.g.alchemy.com/v2
    name: Lumia Prism
  - url: https://lumia-testnet.g.alchemy.com/v2
    name: Lumia Testnet
