info:
  title: Alchemy opBNB JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for opBNB.
  version: 0.0.0
servers:
  - url: https://opbnb-mainnet.g.alchemy.com/v2
    name: opBNB Mainnet
  - url: https://opbnb-testnet.g.alchemy.com/v2
    name: opBNB Testnet
