info:
  title: Alchemy Shape JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Shape.
  version: 0.0.0
servers:
  - url: https://shape-mainnet.g.alchemy.com/v2
    name: Shape Mainnet
  - url: https://shape-sepolia.g.alchemy.com/v2
    name: Shape Sepolia
