# TODO: Need to sync with Fern to get support for specific methods on specific chains
info:
  title: Alchemy Debug API API JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Debug API.
  version: 0.0.0
servers:
  - url: https://eth-mainnet.g.alchemy.com/v2/
    name: Mainnet
  - url: https://eth-sepolia.g.alchemy.com/v2/
    name: Sepolia
