info:
  title: Alchemy Flow JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Flow.
  version: 0.0.0
servers:
  - url: https://flow-mainnet.g.alchemy.com/v2
    name: Flow Mainnet
  - url: https://flow-testnet.g.alchemy.com/v2
    name: Flow Testnet
