info:
  title: Alchemy Astar JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Astar.
  version: 0.0.0
servers:
  - url: https://astar-mainnet.g.alchemy.com/v2
    name: Astar Mainnet