info:
  title: Alchemy Soneium JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Soneium.
  version: 0.0.0
servers:
  - url: https://soneium-mainnet.g.alchemy.com/v2/
    name: Soneium Mainnet
  - url: https://soneium-minato.g.alchemy.com/v2/
    name: Soneium Minato
