info:
  title: Alchemy CrossFi JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for CrossFi.
  version: 0.0.0
servers:
  - url: https://crossfi-mainnet.g.alchemy.com/v2/
    name: CrossFi Mainnet
  - url: https://crossfi-testnet.g.alchemy.com/v2/
    name: CrossFi Testnet
