info:
  title: Alchemy Arbitrum Nova JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Arbitrum Nova.
  version: 0.0.0
servers:
  - url: https://arbnova-mainnet.g.alchemy.com/v2
    name: Arbitrum Nova Mainnet
