info:
  title: Alchemy Rootstock JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Rootstock.
  version: 0.0.0
servers:
  - url: https://rootstock-mainnet.g.alchemy.com/v2
    name: Rootstock Mainnet
  - url: https://rootstock-testnet.g.alchemy.com/v2
    name: Rootstock Testnet
