info:
  title: Alchemy Arbitrum JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Arbitrum.
  version: 0.0.0
servers:
  - url: https://arb-mainnet.g.alchemy.com/v2/
    name: Arbitrum Mainnet
  - url: https://arb-sepolia.g.alchemy.com/v2/
    name: Arbitrum Sepolia
