info:
  title: Alchemy Core API JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Core API.
  version: 0.0.0
servers:
  [
    { "url": "https://eth-mainnet.g.alchemy.com/v2", "name": "Mainnet" },
    { "url": "https://eth-holesky.g.alchemy.com/v2", "name": "Holesky" },
    {
      "url": "https://opt-mainnet.g.alchemy.com/v2",
      "name": "Optimism Mainnet",
    },
    {
      "url": "https://opt-sepolia.g.alchemy.com/v2",
      "name": "Optimism Sepolia",
    },
  ]
