info:
  title: Alchemy Ethereum JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Ethereum.
  version: 0.0.0
servers:
  - url: https://eth-mainnet.g.alchemy.com/v2/
    name: Ethereum Mainnet
  - url: https://eth-sepolia.g.alchemy.com/v2/
    name: Ethereum Sepolia
  - url: https://eth-holesky.g.alchemy.com/v2/
    name: Ethereum Holesky
