info:
  title: Alchemy Lens JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Lens.
  version: 0.0.0
servers:
  - url: https://lens-mainnet.g.alchemy.com/v2/
    name: Lens Mainnet
  - url: https://lens-sepolia.g.alchemy.com/v2/
    name: Lens Sepolia
