info:
  title: Alchemy zkSync JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for zkSync.
  version: 0.0.0
servers:
  - url: https://zksync-mainnet.g.alchemy.com/v2
    name: zkSync Mainnet
  - url: https://zksync-sepolia.g.alchemy.com/v2
    name: zkSync Sepolia
