info:
  title: Alchemy Scroll JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Scroll.
  version: 0.0.0
servers:
  - url: https://scroll-mainnet.g.alchemy.com/v2/
    name: Scroll Mainnet
  - url: https://scroll-sepolia.g.alchemy.com/v2/
    name: Scroll Sepolia
