info:
  title: Alchemy ApeChain JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for ApeChain.
  version: 0.0.0
servers:
  - url: https://apechain-mainnet.g.alchemy.com/v2/
    name: ApeChain Mainnet
  - url: https://apechain-curtis.g.alchemy.com/v2/
    name: ApeChain Curtis
