info:
  title: Alchemy Bitcoin JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Bitcoin.
  version: 0.0.0
servers:
  - url: https://bitcoin-mainnet.alchemy-blast.com/v2
    name: Bitcoin Mainnet
  - url: https://bitcoin-mainnet.alchemy-blast.com/v2
    name: Bitcoin Testnet
