info:
  title: Alchemy Geist JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Geist.
  version: 0.0.0
servers:
  - url: https://geist-mainnet.g.alchemy.com/v2/
    name: Geist Mainnet
  - url: https://geist-polter.g.alchemy.com/v2/
    name: Geist Polter
