info:
  title: Alchemy Gnosis JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Gnosis.
  version: 0.0.0
servers:
  - url: https://gnosis-mainnet.g.alchemy.com/v2
    name: Gnosis Mainnet
  - url: https://gnosis-chiado.g.alchemy.com/v2
    name: Gnosis Chiado
