name: "Add aa-sdk docs to fern"
description: "Checks out aa-sdk repository with sparse checkout and copies docs to fern/docs/account-kit"

runs:
  using: "composite"
  steps:
    - name: Sparse Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: alchemyplatform/aa-sdk
        path: aa-sdk
        sparse-checkout: |
          docs/
        sparse-checkout-cone-mode: true

    - name: Copy docs to workspace and insert into fern
      shell: bash
      run: |
        mkdir -p fern/docs/account-kit
        cp -r aa-sdk/docs/* fern/docs/account-kit
        fern/docs/account-kit/scripts/insert-docs.sh
