# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2022-10-07

openapi: 3.1.0
info:
  title: "Beta APIs"
  version: "1.0"
servers:
  - url: "https://api.g.alchemy.com/data/v1"
paths:
  "/{apiKey}/transactions/history/by-address":
    post:
      $ref: "./transactions/history/by-address.yaml"
