info:
  title: Alchemy Sonic JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Sonic.
  version: 0.0.0
servers:
  - url: https://sonic-mainnet.g.alchemy.com/v2/
    name: Sonic Mainnet
  - url: https://sonic-blaze.g.alchemy.com/v2/
    name: Sonic Blaze
