info:
  title: Alchemy Sui JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Sui.
  version: 0.0.0
servers:
  - url: https://sui-mainnet.alchemy-blast.com/v2
    name: Sui Mainnet
  - url: https://sui-sepolia.alchemy-blast.com/v2
    name: Sui Testnet
