info:
  title: Alchemy Unichain JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Unichain.
  version: 0.0.0
servers:
  - url: https://unichain-mainnet.g.alchemy.com/v2/
    name: Unichain Mainnet
  - url: https://unichain-sepolia.g.alchemy.com/v2/
    name: Unichain Sepolia
