info:
  title: Alchemy Sei JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Sei.
  version: 0.0.0
servers:
  - url: https://sei-mainnet.g.alchemy.com/v2
    name: Sei Mainnet
  - url: https://sei-testnet.g.alchemy.com/v2
    name: Sei Testnet
