info:
  title: Alchemy Worldchain JSON-RPC Specification
  description: A specification of the standard JSON-RPC methods for Worldchain.
  version: 0.0.0
servers:
  - url: https://worldchain-mainnet.g.alchemy.com/v2/
    name: Worldchain Mainnet
  - url: https://worldchain-sepolia.g.alchemy.com/v2/
    name: Worldchain Sepolia
