name: Index Changelog

on:
  push:
    branches:
      - main
    paths:
      - "fern/changelog/**"

jobs:
  index-changelog:
    name: Index Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run changelog indexer
        run: pnpm index:changelog
        env:
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
