name: Run checks on PR

on: pull_request

jobs:
  open-api-specs:
    name: OpenAPI Specs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Validate REST API specs
        run: pnpm run generate:rest

  rpc-specs:
    name: JSON-RPC Specs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Validate RPC specs
        run: pnpm run generate:rpc

  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Run ESLint
        run: pnpm run lint:eslint

  generate-preview:
    name: Generate Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Preview
        uses: ./.github/actions/generate-preview
        with:
          github-token: ${{ github.token }}
          branch: ${{ github.head_ref }}
          kv-rest-api-url: ${{ secrets.KV_REST_API_URL }}
          kv-rest-api-token: ${{ secrets.KV_REST_API_TOKEN }}
          docs-site-url: ${{ secrets.DOCS_SITE_URL }}
          docs-site-api-key: ${{ secrets.DOCS_SITE_API_KEY }}

  link-check:
    name: Link Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--config lychee.toml 'content/**/*.mdx'"
          fail: true
