name: Validate Docs on PR

on:
  pull_request:
    branches: [main]

jobs:
  open-api-specs:
    name: OpenAPI Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Validate REST API specs
        run: pnpm run generate:rest

  rpc-specs:
    name: JSON-RPC Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Validate RPC specs
        run: pnpm run generate:rpc

  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Run ESLint
        run: pnpm run lint:eslint

  fern-check:
    name: Fern Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern
        run: npm install -g fern-api

      - name: Check API is valid
        run: fern check
