name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add aa-sdk docs to fern
        uses: ./.github/actions/sparse-checkout-docs

      - name: Publish Documentation
        uses: ./.github/actions/publish-fern
        id: publish
        with:
          github-token: ${{ github.token }}
          fern-token: ${{ secrets.FERN_TOKEN }}
          environment: docs-production
          ref: ${{ github.ref }}
